ClubEsportivo/Models/ErrorViewModel.cs
namespace ClubEsportivo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClubEsportivo/Models/EsqueciSenha.cs
namespace Jovem_Programador_WEB.Models
{
    public class EsqueciSenha
    {
		private string email;

		public string Email
		{
			get { return email; }
			set { email = value; }
		}

	}
}

ClubEsportivo/Models/Login.cs
namespace Jovem_Programador_WEB.Models
{
    public class Login
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}

ClubEsportivo/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Criar()
        {
            return View();
        }
    }
}

ClubEsportivo/Controllers/EventoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class EventoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClubEsportivo/Controllers/EventoDependenteController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class EventoDependenteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClubEsportivo/Controllers/ExameController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class ExameController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClubEsportivo/Controllers/FaturaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class FaturaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClubEsportivo/Controllers/HomeController.cs
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Jovem_Programador_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClubEsportivo/Controllers/LoginController.cs
using Jovem_Programador_WEB.Data.Repositorio.Interfaces;
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jovem_Programador_WEB.Controllers
{
    public class LoginController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILoginRepositorio _LoginRepositorio;

        public LoginController(IConfiguration configuration, ILoginRepositorio loginRepositorio)
        {
            _configuration = configuration;   
            _LoginRepositorio = loginRepositorio;
        }
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult BuscarLogin(Login login)
        {
            try
            {
                if (login.Usuario == "IndioADM" && login.Senha == "cacique" || login.Senha == "indio123")
                {
                    // Se o usuário for IndioADM e a senha for cacique, redirecionar para a página desejada
                    return RedirectToAction("Index", "Home");
                }

                else if (login.Usuario == "IndioDependente" && login.Senha == "indiofilho")
                {
                    return RedirectToAction("Index", "EventoDependente");
                }

                else
                {
                    var acesso = _LoginRepositorio.ValidarLogin(login);

                    if (acesso != null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    else
                    {
                        TempData["MsgErro"] = "Usuário ou senha incorretos!";
                    }
                }
            }
            catch (Exception)
            {
                TempData["MsgErro"] = "Erro ao buscar dados do usuário";
            }

            return View("Index");
        }

        public IActionResult EsqueciSenha()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EsqueciSenha(string email)
        {
            try
            {
                //Aqui iria um código de envio de email com 


            }
            catch (Exception)
            {
                TempData["MsgErro"] = "Erro ao enviar email";
            }
            return View("EsqueciSenhaCodigo");
        }

        public IActionResult EsqueciSenhaCodigo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EsqueciSenhaCodigo(string codigo)
        {
            try
            {
                //Aqui validaria o código informado


            }
            catch (Exception)
            {
                TempData["MsgErro"] = "Erro ao validar o código";
            }
            return View("NovaSenha");
        }

        public IActionResult NovaSenha()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NovaSenha(string senha, string confirmacaoSenha)
        {
            try
            {



            }
            catch (Exception)
            {
                TempData["MsgErro"] = "Erro ao cadastrar a senha";
            }
            return View("Index");
        }

    }
}

ClubEsportivo/Controllers/ProfessorController.cs
using Jovem_Programador_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Jovem_Programador_WEB.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly IConfiguration _configuration;
        public ProfessorController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            Endereco endereco = new Endereco();

            try
            {
                cep = cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if (result.IsSuccessStatusCode)
                {
                    endereco = JsonSerializer.Deserialize<Endereco>(await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });
                }
                else
                {
                    ViewData["MsgErro"] = "Erro na busca do endereço!";
                }
            }

            catch (Exception)
            {
                throw;
            }

            return View("Endereco", endereco);
        }
    }
}

ClubEsportivo/Views/Cadastro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ClubEsportivo/Views/Cadastro/Index.cshtml
@{
    Layout = "_LayoutDependente";
}

@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}

@model Views_Cadastro_Index
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carousel</title>
    <style>
    .mb-3 {
        width: 50%;
        margin-left: 40px;
    }

    #botaoCadastrar {
        margin-left: 40px;
        background-color: saddlebrown;
        border: none;
        border-radius: 26px;
        cursor: pointer;
        color:#ccc;
    }
    #botaoCadastrar:hover {
        background-color: rgb(227, 123, 49);
        color: rgb(249, 226, 210);
    }
    #voltar {
        background-color: saddlebrown;
        border: none;
        border-radius: 26px;
        cursor: pointer;
        color:#ccc;
    }
    #voltar:hover {
        background-color: rgb(227, 123, 49);
        color: rgb(249, 226, 210);
    }
    #text{
	    border: hidden;
        border-radius: 25px;
        cursor: text;
        width: 360px;
        height: 35px;
        padding-left: 10px;
    }
    </style>
</head>

<div class="text-center">
    <h1 class="display-4">Cadastrar usuário</h1>

</div>
<body>
<form>


    <div class="mb-3">
        <label for="Qual deseja ser">Qual das duas opções abaixo você deseja ser:</label>
        
    </div>
   <div class="mb-3">
    <input name="opção" type="radio" value="1" /> Titular
    <input name="opção" type="radio" value="2" /> Dependente
    </div>


    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" id="text" class="form-control" placeholder="Digite seu nome completo">
    </div>
    <div class="mb-3">
        <label for="Data de nascimento" class="form-label">Data de nascmimento</label>
        <input type="date" id="text" class="form-control">
    </div>
    <div class="mb-3">
        <label for="Informe o seu Email" class="form-label">Email</label>
        <input type="email" id="text" class="form-control" placeholder="Digite seu Email">
    </div>
    <div class="mb-3">
        <label for="nome" class="form-label">CPF</label>
        <input type="text" id="text" class="form-control" placeholder="Digite seu CPF">
    </div>
    <div class="mb-3">
        <label for="nome" class="form-label">CEP</label>
        <input type="text" id="text" class="form-control" placeholder="Digite seu CEP">
    </div>
<div class="mb-3">
    <label for="usuario" class="form-label">Usuário</label>
    <input type="text" id="text" class="form-control"  placeholder="Crie um usuário">
</div>
 
    <div class="mb-3">
        <label for="senha" class="form-label">Senha</label>
        <input type="text" id="text"class="form-control" placeholder="Crie uma senha">
    </div>
    <div class="mb-3">
        <label for="senha" class="form-label">Confirmar senha</label>
        <input type="text" id="text" class="form-control" placeholder="Confirme sua senha">
    </div>
<button id="botaoCadastrar" type="submit" onclick="mensagemTela()" class="btn btn-secundary">Cadastrar</button>
<a class="btn btn-secundary" id="voltar" asp-controller="Login" asp-action="Index" role="button">Voltar</a>
</form>
</body>

<script>
    //Mensagem de cadastro bem sucessido
    function mensagemTela() {
        var nomeElement = document.getElementById('text');
        var nome = nomeElement.value;

        alert(nome + ' foi cadastrado com sucesso!');
    }
    
</script>

ClubEsportivo/Views/Login/EsqueciSenha.cshtml
@{
    Layout = "_LayoutDeslogado";
}
@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@model EsqueciSenha
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Esqueci minha senha</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #button {
            background-color: saddlebrown;
            border: none;
            border-radius: 26px;
            cursor: pointer;
        }

        #button:hover {
            background-color: rgb(227, 123, 49);
            color: rgb(249, 226, 210);
        }

        body {
            background-color: rgb(246, 244, 233);
        }

        #email {
            border: hidden;
            border-radius: 25px;
            background-color: rgb(246, 244, 232);
            cursor: text;
            width: 360px;
            height: 35px;
            padding-left: 10px;
        }
    </style>
</head>
<body>
   
        <div class="container row align-items-center justify-content-center">
            <div class="col-12 col-md-8 col-lg-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <div class="mb-4">
                            <h5>Esqueceu sua senha?</h5>
                            <p class="mb-2">
                            Informe o seu <b>Usuário</b> que iremos enviar o código de recuperação
                            </p>
                        </div>
                    <form asp-controller="Login" asp-action="EsqueciSenha">
                            <div class="mb-3">
                            <label for="email" class="form-label">Usuário</label>
                            <input type="text" id="email" class="form-control" name="email" placeholder="Usuário cadastrado"
                                       required="">

                            </div>
                            <div class="mb-3 d-grid">
                                <button type="submit" id="button" class="btn btn-primary">
                                    Recuperar Senha
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

</body>

</html>

ClubEsportivo/Views/Login/EsqueciSenhaCodigo.cshtml
@{
    Layout = "_LayoutDeslogado";
}
@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@model EsqueciSenha
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Esqueci minha senha</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #button {
            background-color: saddlebrown;
            border: none;
            border-radius: 26px;
            cursor: pointer;
        }

        #button:hover {
            background-color: rgb(227, 123, 49);
            color: rgb(249, 226, 210);
        }

        body {
            background-color: rgb(246, 244, 233);
        }

        #codigo{
            border: hidden;
            border-radius: 25px;
            background-color: rgb(246, 244, 233);
            cursor: text;
            width: 360px;
            height: 35px;
            padding-left: 10px;
        }
    </style>
</head>
<body>

    <div class="container row align-items-center justify-content-center">
        <div class="col-12 col-md-8 col-lg-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="mb-4">
                        <h5>Código de validação</h5>
                        <p class="mb-2">
                            Informe o código que enviamos ao seu email
                        </p>
                    </div>
                    <form asp-controller="Login" asp-action="EsqueciSenhaCodigo">
                        <div class="mb-3">
                            <label for="codigo" class="form-label">Código</label>
                            <input type="text" id="codigo" class="form-control" name="codigo"  placeholder="Código enviado"
                                   required="">

                        </div>
                        <div class="mb-3 d-grid">
                            <button type="submit" id="button" class="btn btn-primary">
                                Validar código
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

<script>

        // Função que será executada após 2 segundos
        function exibirMensagem() {
            alert('Email: Seu código de alteração de senha é 101010');
        }

    // Definindo um atraso de 2 segundos antes de chamar a função
    setTimeout(exibirMensagem, 2000);

</script>
            

ClubEsportivo/Views/Login/Index.cshtml
@{
    Layout = "_LayoutDeslogado";
}

@if (ViewData["MsgErro"] != null)
{
    <div class="alert-danger">
        @ViewData["MsgErro"]
    </div>
}
@model Login
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>tela de login</title>
    <link href="/img/logo03.jpeg" rel="stylesheet" integrity="sha384-4bw+/aepp/yc94hepvnvgizdgic5+vknbqngchekrqn+ptmohdexuppvndjzqiu9" crossorigin="anonymous">
    <style>

        #button {
            background-color: saddlebrown;
            border:none;
            border-radius: 26px;
            cursor:pointer;
        }
        #button:hover{
                background-color: rgb(227, 123, 49);
                color: rgb(249, 226, 210);
        }

        #esqueciSenha{
            text-decoration: none;
            color: black;
        }

        #esqueciSenha:hover{
                color: rgb(107, 107, 107);
        }
            
    </style>
</head>
<body>
    <div class="container mt-4 ">
        <div class="row align-items-center mx-auto col-lg-5">

            
            <form class="p-4 p-md-5 border rounded-3 bg-light" asp-controller="Login" asp-action="BuscarLogin" method="post">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="inputUsuario" placeholder="Usuario" asp-for="Usuario" />
                    <label for="inputUsuario" class="form-label"><i class="fa-solid fa-user fa-shake" style="margin-right: 10px"></i>Usuário</label>
                </div>

                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Senha" asp-for="Senha" />
                    <label for="inputSenha" class="form-label"><i class="fa-solid fa-key fa-shake" style="margin-right: 10px"></i>Senha</label>
                </div>

                <button id="button" class="w-100 btn btn-lg btn-secondary" role="button">Entrar</button>
                
                <button id="button" style="margin-top: 5px;" class="w-100 btn btn-lg btn-secondary" role="button" asp-controller="Cadastro" asp-action="Index">Cadastrar</button>

                <p>               
                <div class="col12  text-center">
                        <a id="esqueciSenha" asp-controller="Login" asp-action="EsqueciSenha" class="link-primary">Esqueci a senha</a>
                </div>
                </p>
            </form>


            <style>
                body {
                    background-color: rgba(36, 19, 9);
                     /* Substitua com a cor desejada em hexadecimal, RGB ou nome da cor */
                }
            </style>

        </div>
     </div>
   
</body>
</html>

ClubEsportivo/Views/Login/NovaSenha.cshtml
@{
	Layout = "_LayoutDeslogado";
}
@if (ViewData["MsgErro"] != null)
{
	<div class="alert-danger">
		@ViewData["MsgErro"]
	</div>
}
@model EsqueciSenha
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Esqueci minha senha</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<style>
		#button {
            background-color: saddlebrown;
            border: none;
            border-radius: 26px;
            cursor: pointer;
        }

        #button:hover {
            background-color: rgb(227, 123, 49);
            color: rgb(249, 226, 210);
        }

        body {
            background-color: rgb(246, 244, 233);
        }

		#senha{
			border: hidden;
			border-radius: 25px;
			background-color: rgb(246, 244, 233);
			cursor: text;
			width: 360px;
			height: 35px;
			padding-left: 10px;
		}

		#confirmacaoSenha {
			border: hidden;
			border-radius: 25px;
			background-color: rgb(246, 244, 233);
			cursor: text;
			width: 360px;
			height: 35px;
			padding-left: 10px;
		}
	</style>
</head>
<body>
	<div class="container row align-items-center justify-content-center">
		<div class="col-12 col-md-8 col-lg-4">
			<div class="card shadow-sm">
				<div class="card-body">
					<div class="mb-4">
						<h5>Cadastro de nova senha</h5>
					</div>
					<form asp-controller="Login" asp-action="NovaSenha">
						<div class="mb-3">
							<label for="senha" class="form-label">Senha</label>
							<input type="text" id="senha" class="form-control" name="senha" placeholder="Nova senha"
								   required="">
						</div>
						<div class="mb-3">
							<label for="confirmacaoSenha" class="form-label">Confirmação da senha</label>
							<input type="text" id="confirmacaoSenha" class="form-control" name="confirmacaoSenha" placeholder="Confirme a senha"
								   required="">

						</div>
						<div class="mb-3 d-grid">
							<button type="submit" id="button" class="btn btn-primary">
								Cadastrar nova senha
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

ClubEsportivo/Views/Professor/Endereco.cshtml
@model Endereco

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Logradouro: @Html.DisplayFor(endereco => endereco.logradouro)</p>
                <p>Bairro: @Html.DisplayFor(endereco => endereco.bairro)</p>
                <p>UF: @Html.DisplayFor(endereco => endereco.uf)</p>
                <p>DDD: @Html.DisplayFor(endereco => endereco.ddd)</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" type="button" asp-controller="Professor" asp-action="Index">Fechar</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#myModal').modal('show');
        });
    </script>
}

ClubEsportivo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem_Programador_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jovem_Programador_WEB.styles.css" asp-append-version="true" />
    <!--FONTE GOOGLE FONTES-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet">
    <!--ICONE FONTAWESOME-->
    <script src="https://kit.fontawesome.com/522fbec30d.js" crossorigin="anonymous"></script>

    <style>
        .navbar{
            margin-bottom: 40px;
            position: fixed;
        }
        .BmVd{
            color: saddlebrown;
        }
        body{
            background-color: rgb(246, 244, 233);
        }
    </style>

</head>
<body>
    <header>


        <nav class="navbar shadow navbar-dark " style="background-color: rgba( 241, 238, 221)">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                    <img src="img/icone-cardapio.png" style="width: 50px; height: 50px">
                </button>
                <center>
                    <h2 style="font-family: Agbalumo" class="BmVd">Bem-vindo</h2>
                </center>
                <img src="img/logo03.jpeg" class="float-right" width="75">
            </div>
        </nav>



        <div class="offcanvas offcanvas-start d-flex flex-column flex-shrink-0 p-3 text-bg-dark" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel" style="width: 280px;">


            <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <img  src="https://img.freepik.com/vetores-premium/ilustracao-de-um-indio-brasileiro_850997-494.jpg?w=740" alt="ERROR" width="50" height="50" class="rounded-circle me-4">
                <span class="fs-5 text-black text-">Admin </span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a asp-controller="Evento" asp-action="Index" class="nav-link text-black" aria-current="page">
                        <i class="fa-regular fa-calendar-days" style="margin-right: 10px"></i>
                        Eventos
                    </a>
                </li>
                <li>
                    <a asp-controller="Fatura" asp-action="Index" class="nav-link text-black">
                        <i class="fa-solid fa-money-bill-1-wave" style="margin-right: 8px"></i>
                        Fatura
                    </a>
                </li>
                <li>
                    <a asp-controller="Exame" asp-action="Index" class="nav-link text-black">
                        <i class="fa-solid fa-microscope" style="margin-right: 10px"></i>
                        Exame
                    </a>
                </li>

            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center text-black text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                        <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                    </svg>
                    <strong></strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                    <li><a class="dropdown-item" asp-controller="Login" asp-action="Index">Sair</a></li>
                </ul>
            </div>
        </div>

      

            
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Jovem_Programador_WEB
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ClubEsportivo/Views/Shared/_LayoutDependente.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem_Programador_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jovem_Programador_WEB.styles.css" asp-append-version="true" />
    <!--FONTE GOOGLE FONTES-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/522fbec30d.js" crossorigin="anonymous"></script>

    <style>
      #sair{
          font-size: 30px;
          margin-left: 10px;
          margin-bottom: 4px;
          cursor: pointer;
          color: saddlebrown;
      }
      h2{
          color: saddlebrown;
      }

      body{
            background-color: rgb(246, 244, 233);
      }
    </style>
</head>

<body>
    <header>

        
        <nav class="navbar shadow navbar-dark " style="background-color: rgba( 241, 238, 221)">
            <div class="container-fluid">
                <a asp-controller="Login" asp-action="Index" id="sair">
                    <i class="fa-solid fa-right-from-bracket fa-rotate-180"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                </button>
                
                <center>
                    <h2 style="font-family: Agbalumo; margin-right: 320px;">Bem-vindo</h2>
                </center>
                <img src="img/logo03.jpeg" class="float-right" width="75">
            </div>
        </nav>

        <div>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
</header>
</body>
</html>